branch-defaults:
  default:
    environment: cppinventory-env
    group_suffix: null
global:
  application_name: cppinventory
  branch: null
  default_ec2_keyname: cpp-eb-deploy
  default_platform: Python 3.11
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
